name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - run: npm install



    - name: Install Railway
      run: npm i -g @railway/cli

    - name: Check if RAILWAY_TOKEN exists
      run: |
        if [ -z "$RAILWAY_TOKEN" ]; then
          echo " RAILWAY_TOKEN is not set"
          exit 1
        else
          echo " RAILWAY_TOKEN is present"
        fi
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}


    - name: Deploy
      run: railway up --service STS_NODE
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}